# agenticai/tools/comment_tool.py
import asyncio
from playwright.async_api import async_playwright, TimeoutError
from langchain.tools import Tool

# Safe import for standalone or package
try:
    from .utils import apply_saved_cookies
except ImportError:
    from utils import apply_saved_cookies

async def comment_tweet(tweet_url, comment_text):
    """
    Navigate to a tweet URL and post a comment.
    Requires saved cookies to be valid (login verification included).
    """
    print(f"📨 Inside comment_tweet for: {tweet_url}")
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        await apply_saved_cookies(context)
        page = await context.new_page()

        # Verify login
        print("🔐 Verifying login status by visiting x.com/home...")
        await page.goto("https://x.com/home", timeout=60000, wait_until="domcontentloaded")
        try:
            composer = page.get_by_test_id('tweetTextarea_0')
            await composer.wait_for(timeout=15000)
            print("✅ Login verified successfully!")
        except TimeoutError:
            print("❌ Login verification failed. Cookies might be invalid or expired.")
            await page.screenshot(path="login_verification_failed.png", full_page=True)
            await browser.close()
            return

        # Navigate to tweet and post comment
        await page.goto(tweet_url, timeout=60000, wait_until="domcontentloaded")
        main_tweet = page.locator('article[data-testid="tweet"]').first
        await main_tweet.wait_for(timeout=15000)
        reply_icon = main_tweet.get_by_test_id('reply')
        await reply_icon.click()
        textbox = page.get_by_test_id('tweetTextarea_0')
        await textbox.wait_for(timeout=10000)
        await textbox.fill(comment_text)
        reply_btn = page.get_by_test_id('tweetButton')
        await reply_btn.click()
        print(f"✅ Commented: {tweet_url}")
        await browser.close()

# --- LangChain tool ---
comment_tool = Tool.from_function(
    name="comment_tweet",
    func=comment_tweet,
    description="Posts a comment on a tweet using a given URL and text. The text is generated by LLM."
)

# Optional: standalone test
if __name__ == "__main__":
    import asyncio
    test_url = "https://x.com/some_tweet_url"
    test_comment = "This is a test comment generated by LLM."
    asyncio.run(comment_tweet(test_url, test_comment))
